# Generated by Django 3.1.4 on 2021-01-03 20:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=1200)),
                ('page', models.CharField(max_length=200)),
                ('range', models.CharField(max_length=200)),
                ('components', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('ritual', models.BooleanField(default=False)),
                ('duration', models.CharField(max_length=100)),
                ('concentration', models.BooleanField(default=False)),
                ('casting_time', models.CharField(max_length=200)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('school', models.CharField(max_length=100)),
                ('klass', models.ManyToManyField(to='spells.Klass')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
